export {default as Header} from "./Header/Header"
export {default as Intro} from "./Intro/Intro"
export {default as Profile} from "./Profile/Profile"
export {default as LogIn} from "./LogIn/LogIn"
export {default as SignUp} from "./SignUp/SignUp"
export {default as Footer} from "./Footer/Footer"
